jobs:
- deployment: build
  timeoutInMinutes: 180
  displayName: ${{parameters.stage}}
  environment: ${{parameters.stage}}
  strategy:
    runOnce:
      deploy:
        steps:
          - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
            displayName: 'Create/Update Stack: todo-api-${{parameters.stage}}'
            inputs:
              awsCredentials: '${{parameters.config.awsCredentials}}'
              regionName: 'eu-west-1'
              stackName: 'todo-api-${{parameters.stage}}'
              timeoutInMins: 120
              changeSetName: "$(Build.BuildNumber)"
              templateFile: '$(Pipeline.Workspace)/todo-cloudformation/todo-api.yml'
              templateParametersSource: inline
              templateParameters: |
                - ParameterKey: Stage
                  ParameterValue: $(Environment.Name)
                - ParameterKey: BuildReference
                  ParameterValue: "$(Build.BuildNumber)"
                - ParameterKey: DeployBucket
                  ParameterValue: "${{parameters.config.deployBucket}}"
              tags: STAGE=${{parameters.stage}}
              warnWhenNoWorkNeeded: false