jobs:
- job: build_artefacts
  displayName: Package AWS artifacts
  steps:
    - task: CopyFiles@2
      displayName: Copy source files
      inputs:
        SourceFolder: src/
        TargetFolder: $(Build.ArtifactStagingDirectory)/src/

    - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
      displayName: 'Upload files to S3 (non-prod)'
      inputs:
        awsCredentials: 'todo-aws-dev'
        regionName: 'eu-west-1'
        bucketName: 'todo-deploy-bucket'
        sourceFolder: '$(Build.ArtifactStagingDirectory)/src/'
        targetFolder: $(Build.BuildNumber)
        globExpressions: '**'
        createBucket: true

    - publish: $(Build.ArtifactStagingDirectory)/src/cloudformation
      artifact: todo-cloudformation
